language: node_js
node_js:
  - 12.14

install:
  - npm install hexo
  - npm install hexo-renderer-pug 
  - npm install hexo-renderer-sass
  - npm install hexo-generator-feed

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

notifications:

branches:
  only:
    - master

cache:
  directories:
    - node_modules

env:
 global:
   - GH_REF: github.com/zhengr/Claudia-theme-blog.git
